import { FC } from "react";
import { getLayout } from "../../layouts/MainLayout";
import Head from "next/head";
import path from "path";
import fs from "fs";
import { postFilePaths, POSTS_PATH } from "../../utils/mdxUtils";
import matter from "gray-matter";
import Link from "next/link";

const Blog: FC = ({ posts }) => {
  return (
    <>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{" "}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
          <br />
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`/blog/${post.filePath.replace(/\.mdx?$/, "")}`}
              href={`/blog/[slug]`}
            >
              <a>{post.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </>
  );
};

export function getStaticProps() {
  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
    const { content, data } = matter(source);

    return {
      content,
      data,
      filePath,
    };
  });

  return { props: { posts } };
}

Blog.getLayout = getLayout;

export default Blog;
